production:
  sync_transactions:
    class: SyncJob
    queue: default
    args:
      - days_back: 2
    schedule: every 2 hours
  categorise_transactions:
    class: CategoriseJob
    queue: default
    schedule: every 2 hours
